version: "2"
# Docker compose file to compose necessary docker containers
# on ECS in order to build develop environment
services:
  # Mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /mydata/mysql/log:/var/log/mysql
      - /mydata/mysql/data:/var/lib/mysql
      - /mydata/mysql/conf:/etc/mysql
      - /mydata/mysql/mysql-files:/var/lib/mysql-files
    ports:
      - "3306:3306"
    restart: always
  # Redis
  redis:
    container_name: redis
    image: redis
    volumes:
      - /mydata/redis/data:/data
      - /mydata/redis/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --appendonly yes
    ports:
      - "6379:6379"
    restart: always
  # ElasticSearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.2
    environment:
      - ES_JAVA_OPTS="-Xms64m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - /mydata/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  # Kibana
  kibana:
    container_name: kibana
    image: kibana:7.6.2
    web:
      links:
        - "elasticsearch:elastisearch"
    ports:
      - "5601:5601"
    restart: always
  # Nacos
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
  nacos-mysql:
    container_name: mysql5.7
    image: nacos/nacos-mysql:5.7
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure
  # Rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9
    hostname: myRabbit
    volumes:
      - /mydata/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
    restart: always
  # Rabbitmq web management plugin
  rabbitmq-management:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    hostname: myRabbit
    ports: 
      - "15672:15672"
    restart: always

