spring:
  cloud:
    gateway:
      routes:
        - id: third_party_route
          uri: lb://blkmkt-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: auth_server_route
          uri: lb://blkmkt-auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: good_route
          uri: lb://blkmkt-good
          predicates:
            - Path=/api/good/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://blkmkt-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: user_route
          uri: lb://blkmkt-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: forum_route
          uri: lb://blkmkt-forum
          predicates:
            - Path=/api/forum/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
