swagger: '2.0'
info:
  description: 这是一篇关于商品的API文档
  version: 1.0.0
  title: 商品API文档
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: ShZh7
    url: 'https://github.com/Sh-Zh-7'
    email: zhihaoshen7@qq.com
  license:
    name: GPL-v3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'
host: 'localhost:7000'
basePath: /
tags:
  - name: 商品
    description: 所有关于商品的内容
  - name: 商品评论
    description: 所有关于商品评论的内容
  - name: 商品评论回复
    description: 所有关于商品评论回复的内容
paths:
  /good/good/:
    post:
      tags:
        - 商品
      summary: 保存信息
      description: 保存信息
      operationId: saveUsingPOST_2
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: good
          description: good entity
          required: true
          schema:
            $ref: '#/definitions/GoodEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    put:
      tags:
        - 商品
      summary: 更新信息
      description: 更新信息
      operationId: updateUsingPUT_2
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: good
          description: good entity
          required: true
          schema:
            $ref: '#/definitions/GoodEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    delete:
      tags:
        - 商品
      summary: 删除
      description: 删除信息
      operationId: deleteUsingDELETE_2
      produces:
        - '*/*'
      parameters:
        - in: body
          name: ids
          description: id array
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
  /good/good/list:
    get:
      tags:
        - 商品
      summary: 所有信息
      description: 根据分页参数（可缺省）获取信息
      operationId: listUsingGET_2
      produces:
        - '*/*'
      parameters:
        - name: pageNo
          in: query
          description: Number of pages
          required: false
          type: integer
          format: int64
        - name: pageSize
          in: query
          description: Size of pages
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«PageUtils«GoodEntity»»'
  '/good/good/{id}':
    get:
      tags:
        - 商品
      summary: 信息
      description: 获取指定id的信息
      operationId: infoUsingGET_2
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«GoodEntity»'
  /good/good_comment/:
    post:
      tags:
        - 商品评论
      summary: 保存信息
      description: 保存信息
      operationId: saveUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: goodComment
          description: goodComment entity
          required: true
          schema:
            $ref: '#/definitions/GoodCommentEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    put:
      tags:
        - 商品评论
      summary: 更新信息
      description: 更新信息
      operationId: updateUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: goodComment
          description: goodComment entity
          required: true
          schema:
            $ref: '#/definitions/GoodCommentEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    delete:
      tags:
        - 商品评论
      summary: 删除
      description: 删除信息
      operationId: deleteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - in: body
          name: ids
          description: id array
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
  /good/good_comment/list:
    get:
      tags:
        - 商品评论
      summary: 所有信息
      description: 根据分页参数（可缺省）获取信息
      operationId: listUsingGET
      produces:
        - '*/*'
      parameters:
        - name: pageNo
          in: query
          description: Number of pages
          required: false
          type: integer
          format: int64
        - name: pageSize
          in: query
          description: Size of pages
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«PageUtils«GoodCommentEntity»»'
  '/good/good_comment/{id}':
    get:
      tags:
        - 商品评论
      summary: 信息
      description: 获取指定id的信息
      operationId: infoUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«GoodCommentEntity»'
  /good/good_comment_replay/:
    post:
      tags:
        - 商品评论回复
      summary: 保存信息
      description: 保存信息
      operationId: saveUsingPOST_1
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: goodCommentReplay
          description: goodCommentReplay entity
          required: true
          schema:
            $ref: '#/definitions/GoodCommentReplayEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    put:
      tags:
        - 商品评论回复
      summary: 更新信息
      description: 更新信息
      operationId: updateUsingPUT_1
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: goodCommentReplay
          description: goodCommentReplay entity
          required: true
          schema:
            $ref: '#/definitions/GoodCommentReplayEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    delete:
      tags:
        - 商品评论回复
      summary: 删除
      description: 删除信息
      operationId: deleteUsingDELETE_1
      produces:
        - '*/*'
      parameters:
        - in: body
          name: ids
          description: id array
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
  /good/good_comment_replay/list:
    get:
      tags:
        - 商品评论回复
      summary: 所有信息
      description: 根据分页参数（可缺省）获取信息
      operationId: listUsingGET_1
      produces:
        - '*/*'
      parameters:
        - name: pageNo
          in: query
          description: Number of pages
          required: false
          type: integer
          format: int64
        - name: pageSize
          in: query
          description: Size of pages
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«PageUtils«GoodCommentReplayEntity»»'
  '/good/good_comment_replay/{id}':
    get:
      tags:
        - 商品评论回复
      summary: 信息
      description: 获取指定id的信息
      operationId: infoUsingGET_1
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«GoodCommentReplayEntity»'
definitions:
  GoodCommentEntity:
    type: object
    properties:
      content:
        type: string
        description: 内容
      contentType:
        type: integer
        format: int32
        example: 1
        description: '评论类型[0 - 对商品的直接评论，1 - 对评论的回复]'
      createTime:
        type: string
        format: date-time
        description: 创建时间
      goodId:
        type: integer
        format: int32
        example: 2
        description: 货物id
      id:
        type: integer
        format: int32
        example: 1
        description: id
      userId:
        type: integer
        format: int32
        example: 3
        description: 用户id
    title: GoodCommentEntity
  GoodCommentReplayEntity:
    type: object
    properties:
      commentId:
        type: integer
        format: int64
        example: 2
        description: 评论id
      id:
        type: integer
        format: int64
        example: 1
        description: id
      replyId:
        type: integer
        format: int64
        example: 3
        description: 回复id
    title: GoodCommentReplayEntity
  GoodEntity:
    type: object
    properties:
      cancelTime:
        type: string
        format: date-time
        description: 取消时间
      createTime:
        type: string
        format: date-time
        description: 创建时间
      currentNum:
        type: integer
        format: int32
        example: 233
        description: 当前数量
      goodImgUrl:
        type: string
        example: baidu.com
        description: 商品图片的url
      gtype:
        type: string
        example: 国创
        description: 分类
      id:
        type: integer
        format: int32
        example: 1
        description: 货物id
      name:
        type: string
        example: 华为手机
        description: 货物名称
      ownerId:
        type: integer
        format: int32
        example: 2
        description: 卖家id
      price:
        type: integer
        format: int32
        example: 4399
        description: 价格
      totalNum:
        type: integer
        format: int32
        example: 2333
        description: 总数
    title: GoodEntity
  PageUtils«GoodCommentEntity»:
    type: object
    properties:
      currPage:
        type: integer
        format: int32
        example: 1
        description: 当前页数
      list:
        type: array
        description: 集合
        items:
          $ref: '#/definitions/GoodCommentEntity'
      pageSize:
        type: integer
        format: int32
        example: 10
        description: 每页记录数
      totalCount:
        type: integer
        format: int32
        example: 1
        description: 总记录数
      totalPage:
        type: integer
        format: int32
        example: 1
        description: 总页数
    title: PageUtils«GoodCommentEntity»
  PageUtils«GoodCommentReplayEntity»:
    type: object
    properties:
      currPage:
        type: integer
        format: int32
        example: 1
        description: 当前页数
      list:
        type: array
        description: 集合
        items:
          $ref: '#/definitions/GoodCommentReplayEntity'
      pageSize:
        type: integer
        format: int32
        example: 10
        description: 每页记录数
      totalCount:
        type: integer
        format: int32
        example: 1
        description: 总记录数
      totalPage:
        type: integer
        format: int32
        example: 1
        description: 总页数
    title: PageUtils«GoodCommentReplayEntity»
  PageUtils«GoodEntity»:
    type: object
    properties:
      currPage:
        type: integer
        format: int32
        example: 1
        description: 当前页数
      list:
        type: array
        description: 集合
        items:
          $ref: '#/definitions/GoodEntity'
      pageSize:
        type: integer
        format: int32
        example: 10
        description: 每页记录数
      totalCount:
        type: integer
        format: int32
        example: 1
        description: 总记录数
      totalPage:
        type: integer
        format: int32
        example: 1
        description: 总页数
    title: PageUtils«GoodEntity»
  Response:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      msg:
        type: string
        example: success
    title: Response
  ResponseWithData«GoodCommentEntity»:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      data:
        $ref: '#/definitions/GoodCommentEntity'
      msg:
        type: string
        example: success
    title: ResponseWithData«GoodCommentEntity»
  ResponseWithData«GoodCommentReplayEntity»:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      data:
        $ref: '#/definitions/GoodCommentReplayEntity'
      msg:
        type: string
        example: success
    title: ResponseWithData«GoodCommentReplayEntity»
  ResponseWithData«GoodEntity»:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      data:
        $ref: '#/definitions/GoodEntity'
      msg:
        type: string
        example: success
    title: ResponseWithData«GoodEntity»
  ResponseWithData«PageUtils«GoodCommentEntity»»:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      data:
        $ref: '#/definitions/PageUtils«GoodCommentEntity»'
      msg:
        type: string
        example: success
    title: ResponseWithData«PageUtils«GoodCommentEntity»»
  ResponseWithData«PageUtils«GoodCommentReplayEntity»»:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      data:
        $ref: '#/definitions/PageUtils«GoodCommentReplayEntity»'
      msg:
        type: string
        example: success
    title: ResponseWithData«PageUtils«GoodCommentReplayEntity»»
  ResponseWithData«PageUtils«GoodEntity»»:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 200
      data:
        $ref: '#/definitions/PageUtils«GoodEntity»'
      msg:
        type: string
        example: success
    title: ResponseWithData«PageUtils«GoodEntity»»