swagger: '2.0'
info:
  description: 这是一篇关于订单的API文档
  version: 1.0.0
  title: 订单API文档
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: ShZh7
    url: 'https://github.com/Sh-Zh-7'
    email: zhihaoshen7@qq.com
  license:
    name: GPL-v3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'
host: 'localhost:8000'
basePath: /
tags:
  - name: 订单
    description: 所有关于订单的内容
paths:
  /order/order/:
    post:
      tags:
        - 订单
      summary: 保存信息
      description: 保存信息
      operationId: saveUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: order
          description: order entity
          required: true
          schema:
            $ref: '#/definitions/OrderEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    put:
      tags:
        - 订单
      summary: 更新信息
      description: 更新信息
      operationId: updateUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: order
          description: order entity
          required: true
          schema:
            $ref: '#/definitions/OrderEntity'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
    delete:
      tags:
        - 订单
      summary: 删除
      description: 删除信息
      operationId: deleteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - in: body
          name: ids
          description: id array
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
  /order/order/list:
    get:
      tags:
        - 订单
      summary: 所有信息
      description: 根据分页参数（可缺省）获取信息
      operationId: listUsingGET
      produces:
        - '*/*'
      parameters:
        - name: pageNo
          in: query
          description: Number of pages
          required: false
          type: integer
          format: int64
        - name: pageSize
          in: query
          description: Size of pages
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«PageUtils«OrderEntity»»'
  '/order/order/{id}':
    get:
      tags:
        - 订单
      summary: 信息
      description: 获取指定id的信息
      operationId: infoUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithData«OrderEntity»'
definitions:
  OrderEntity:
    type: object
    properties:
      goodId:
        type: integer
        format: int32
        example: 2
        description: 货物id
      id:
        type: integer
        format: int32
        example: 1
        description: 订单号
      userId:
        type: integer
        format: int32
        example: 3
        description: 用户id
    title: OrderEntity
  PageUtils«OrderEntity»:
    type: object
    properties:
      currPage:
        type: integer
        format: int32
        example: 1
        description: 当前页数
      list:
        type: array
        description: 集合
        items:
          $ref: '#/definitions/OrderEntity'
      pageSize:
        type: integer
        format: int32
        example: 10
        description: 每页记录数
      totalCount:
        type: integer
        format: int32
        example: 1
        description: 总记录数
      totalPage:
        type: integer
        format: int32
        example: 1
        description: 总页数
    title: PageUtils«OrderEntity»